### GET token from Auth0
curl --request DELETE \
  --url https://localhost/5122/catalog/3 \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjAwNHlGc1lUN0lqcTFXNUF5VU9jSSJ9.eyJpc3MiOiJodHRwczovL2Rldi16Nm0yamhwNnVtNmNud2VuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiIwOHZVeUJtZFk1THc5SUNSelRKdHFBNXhtVUR1VUtSV0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9zY3Jhd255LXNwaWRlci8iLCJpYXQiOjE2ODI4ODg1MzAsImV4cCI6MTY4Mjk3NDkzMCwiYXpwIjoiMDh2VXlCbWRZNUx3OUlDUnpUSnRxQTV4bVVEdVVLUlciLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.yluroq0MJ32HTm2YfFIPjRyfLarhioaPLfVRZ6pmKjrwxQ67WimZI0CpvI-OfnR1Fm_2swNKd10BE65epNJ5nfjJDSzD--KB4UvA1T-Ozzl9rGss8i5x2CY9zw7GvcWzMCVyK5Ee5B_uIQbCq5G-BXSUb4OEhFFnAKuJkM223-sE1Lf2woEtEJM_LBNusz42LMMnJxefLC0-Gu7s-PuKcF88FyTV1iskP0oYJ4xeeS2lUKn62A6pJKcHXp-Tqt3MlVJXXMoxx5VuqbgjgA0TDO-Hn25aSN5SJuYuAdom32mbq-5NQaj4pcRGESsKIneFeyUL1MIGXj3_MWjm-y2KlQ' 
 